CREATE TABLE [dwh].[sf_Account] (
    [Academic_Sub_Record_Type__c]                        NVARCHAR (255)     NULL,
    [accHierarchy__Hierarchy_Parents__c]                 NVARCHAR (MAX)     NULL,
    [accHierarchy__TopParentId__c]                       NVARCHAR (18)      NULL,
    [Account_Manager__c]                                 NVARCHAR (18)      NULL,
    [Account_Payable_Contact__c]                         NVARCHAR (255)     NULL,
    [Account_Quick_Notes__c]                             NVARCHAR (MAX)     NULL,
    [Account_Status__c]                                  NVARCHAR (255)     NULL,
    [AccountNumber]                                      NVARCHAR (40)      NULL,
    [AccountSource]                                      NVARCHAR (255)     NULL,
    [Additional_Invoicing_Terms__c]                      NVARCHAR (255)     NULL,
    [Affiliation_Agreement__c]                           DATE               NULL,
    [AnnualRevenue]                                      NUMERIC (18)       NULL,
    [Apprenticeship_Activity__c]                         NVARCHAR (255)     NULL,
    [Apprenticeship_Comments__c]                         NVARCHAR (250)     NULL,
    [Approval_Category__c]                               NVARCHAR (255)     NULL,
    [Approved_Courses_and_Programs__c]                   NVARCHAR (MAX)     NULL,
    [Attendance_Records_Required__c]                     NVARCHAR (255)     NULL,
    [Attendance_Report_Timeframe__c]                     NVARCHAR (255)     NULL,
    [Billing_Account_Name__c]                            NVARCHAR (255)     NULL,
    [Billing_Contact_Name__c]                            NVARCHAR (35)      NULL,
    [Billing_Email__c]                                   NVARCHAR (80)      NULL,
    [Billing_Notes__c]                                   NVARCHAR (MAX)     NULL,
    [Billing_Phone__c]                                   NVARCHAR (40)      NULL,
    [BillingCity]                                        NVARCHAR (40)      NULL,
    [BillingCountry]                                     NVARCHAR (80)      NULL,
    [BillingCountryCode]                                 NVARCHAR (50)      NULL,
    [BillingGeocodeAccuracy]                             NVARCHAR (50)      NULL,
    [BillingLatitude]                                    NUMERIC (33, 15)   NULL,
    [BillingLongitude]                                   NUMERIC (33, 15)   NULL,
    [BillingPostalCode]                                  NVARCHAR (20)      NULL,
    [BillingState]                                       NVARCHAR (80)      NULL,
    [BillingStateCode]                                   NVARCHAR (50)      NULL,
    [BillingStreet]                                      NVARCHAR (255)     NULL,
    [blng__BillToContact__c]                             NVARCHAR (18)      NULL,
    [blng__CustomerProfileId__c]                         NVARCHAR (50)      NULL,
    [blng__DefaultPaymentType__c]                        NVARCHAR (50)      NULL,
    [Career_Services_Opt_Out__c]                         BIT                NULL,
    [Career_Services_Rep__c]                             NVARCHAR (255)     NULL,
    [Case_Safe_ID_acct__c]                               NVARCHAR (1300)    NULL,
    [Channel_Opportunity__c]                             NVARCHAR (255)     NULL,
    [Cohort_Opt_Out__c]                                  BIT                NULL,
    [Contact_Email__c]                                   NVARCHAR (80)      NULL,
    [Contact_Name__c]                                    NVARCHAR (255)     NULL,
    [Contact_Phone__c]                                   NVARCHAR (40)      NULL,
    [Contract_Application_Submitted_Date__c]             DATE               NULL,
    [Contract_Notes__c]                                  NVARCHAR (MAX)     NULL,
    [Contract_Renewal_Date__c]                           DATE               NULL,
    [Count_of_Enrolled_Student__c]                       NUMERIC (18)       NULL,
    [Created_Date__c]                                    DATE               NULL,
    [CreatedById]                                        NVARCHAR (18)      NULL,
    [CreatedDate]                                        DATETIMEOFFSET (0) NULL,
    [Date_of_Last_Enrollment__c]                         DATE               NULL,
    [Description]                                        NVARCHAR (MAX)     NULL,
    [DOZISF__ZoomInfo_Enrich_Status__c]                  NVARCHAR (255)     NULL,
    [DOZISF__ZoomInfo_First_Updated__c]                  DATETIMEOFFSET (0) NULL,
    [DOZISF__ZoomInfo_Id__c]                             NVARCHAR (30)      NULL,
    [DOZISF__ZoomInfo_InboxAI_ID__c]                     NVARCHAR (255)     NULL,
    [DOZISF__ZoomInfo_Last_Updated__c]                   DATETIMEOFFSET (0) NULL,
    [Employer_Account_Type__c]                           NVARCHAR (MAX)     NULL,
    [Employer_Clinical_Site_Approved__c]                 NVARCHAR (255)     NULL,
    [Facilitator_Fee__c]                                 NUMERIC (20, 2)    NULL,
    [Fax]                                                NVARCHAR (40)      NULL,
    [Featured_Employer__c]                               DATE               NULL,
    [Funding_Source__c]                                  NVARCHAR (255)     NULL,
    [goog_alert__Google_Alert_URL__c]                    NVARCHAR (255)     NULL,
    [Grant_Term__c]                                      NVARCHAR (255)     NULL,
    [HEC_Approval__c]                                    NVARCHAR (255)     NULL,
    [HEC_Approved__c]                                    NVARCHAR (255)     NULL,
    [HEC_Contact__c]                                     NVARCHAR (20)      NULL,
    [HEC_Email__c]                                       NVARCHAR (80)      NULL,
    [HEC_Phone_Number__c]                                NVARCHAR (40)      NULL,
    [HI1000__c]                                          BIT                NULL,
    [HI1100__c]                                          BIT                NULL,
    [HI1200__c]                                          BIT                NULL,
    [HI2000__c]                                          BIT                NULL,
    [HI2100__c]                                          BIT                NULL,
    [HI3000__c]                                          BIT                NULL,
    [HI3100__c]                                          BIT                NULL,
    [HI4000__c]                                          BIT                NULL,
    [HI5100__c]                                          BIT                NULL,
    [HI5200__c]                                          BIT                NULL,
    [Id]                                                 NVARCHAR (18)      NULL,
    [Inactive_Status__c]                                 NVARCHAR (255)     NULL,
    [Industry]                                           NVARCHAR (255)     NULL,
    [Invoice_Preference__c]                              NVARCHAR (255)     NULL,
    [Invoicing_Terms__c]                                 NVARCHAR (255)     NULL,
    [IsDeleted]                                          BIT                NULL,
    [IT2000__c]                                          BIT                NULL,
    [IT2100__c]                                          BIT                NULL,
    [IT2200__c]                                          BIT                NULL,
    [IT3000__c]                                          BIT                NULL,
    [Jigsaw]                                             NVARCHAR (20)      NULL,
    [JigsawCompanyId]                                    NVARCHAR (20)      NULL,
    [LastActivityDate]                                   DATE               NULL,
    [LastModifiedById]                                   NVARCHAR (18)      NULL,
    [LastModifiedDate]                                   DATETIMEOFFSET (0) NULL,
    [LastReferencedDate]                                 DATETIMEOFFSET (0) NULL,
    [LastViewedDate]                                     DATETIMEOFFSET (0) NULL,
    [Letter_of_Intent__c]                                DATE               NULL,
    [LID__LinkedIn_Company_Id__c]                        NVARCHAR (80)      NULL,
    [Locations__c]                                       NVARCHAR (50)      NULL,
    [Mailing_Address__c]                                 NVARCHAR (1300)    NULL,
    [Mailing_City__c]                                    NVARCHAR (255)     NULL,
    [Mailing_State__c]                                   NVARCHAR (255)     NULL,
    [Mailing_Street__c]                                  NVARCHAR (255)     NULL,
    [Mailing_ZipCode__c]                                 NVARCHAR (255)     NULL,
    [MasterRecordId]                                     NVARCHAR (18)      NULL,
    [Medcerts_Programs__c]                               NVARCHAR (MAX)     NULL,
    [MedCerts_Region2__c]                                NVARCHAR (1300)    NULL,
    [Multiple_Invoicing__c]                              NVARCHAR (255)     NULL,
    [MyCAA__c]                                           BIT                NULL,
    [NAICS_Code__c]                                      NUMERIC (18)       NULL,
    [NAICS_Description__c]                               NVARCHAR (255)     NULL,
    [Name]                                               NVARCHAR (255)     NULL,
    [NumberOfEmployees]                                  INT                NULL,
    [OwnerId]                                            NVARCHAR (18)      NULL,
    [Ownership]                                          NVARCHAR (255)     NULL,
    [ParentId]                                           NVARCHAR (18)      NULL,
    [Payment_Structure__c]                               NVARCHAR (MAX)     NULL,
    [Phone]                                              NVARCHAR (40)      NULL,
    [PhotoUrl]                                           NVARCHAR (255)     NULL,
    [Power_of_One__c]                                    NUMERIC (20, 2)    NULL,
    [PR_Outreach_Client_Feedback__c]                     NVARCHAR (MAX)     NULL,
    [PR_Outreach_Date__c]                                DATE               NULL,
    [PR_Outreach_RWM_Feedback__c]                        NVARCHAR (MAX)     NULL,
    [PR_Outreach_Title__c]                               NVARCHAR (255)     NULL,
    [PR_Outreach_Type__c]                                NVARCHAR (255)     NULL,
    [QB_Invoice_Terms__c]                                NVARCHAR (255)     NULL,
    [qbdialer__CloseDate__c]                             DATETIMEOFFSET (0) NULL,
    [qbdialer__CloseScore__c]                            NUMERIC (14, 5)    NULL,
    [qbdialer__Dials__c]                                 NUMERIC (18)       NULL,
    [qbdialer__LastCallTime__c]                          DATETIMEOFFSET (0) NULL,
    [qbdialer__Related_Contact_Dials__c]                 NUMERIC (18)       NULL,
    [qbdialer__Related_Contact_LastCallTime__c]          DATETIMEOFFSET (0) NULL,
    [qbdialer__ResponseTime__c]                          NUMERIC (18)       NULL,
    [RA_Fee__c]                                          NUMERIC (20, 2)    NULL,
    [RA_Renewal_Date__c]                                 DATE               NULL,
    [RA_Website__c]                                      NVARCHAR (255)     NULL,
    [Rating]                                             NVARCHAR (255)     NULL,
    [RB_Contact__c]                                      NVARCHAR (25)      NULL,
    [RecordTypeId]                                       NVARCHAR (18)      NULL,
    [Referral_Percentage__c]                             NUMERIC (20, 2)    NULL,
    [Referral_Process_for_Grant_Funding__c]              NVARCHAR (1000)    NULL,
    [Referral_to_B2B__c]                                 DATE               NULL,
    [Region_ID__c]                                       NVARCHAR (255)     NULL,
    [Regional_Approved__c]                               NVARCHAR (255)     NULL,
    [Regional_Board__c]                                  NVARCHAR (18)      NULL,
    [Registered_Agent__c]                                NVARCHAR (50)      NULL,
    [Required_Credential__c]                             NUMERIC (7, 2)     NULL,
    [Required_Performance__c]                            NUMERIC (7, 2)     NULL,
    [Required_Performance_In_Field__c]                   NUMERIC (7, 2)     NULL,
    [Revenue__c]                                         NUMERIC (20, 2)    NULL,
    [Revenue_Share__c]                                   NUMERIC (18)       NULL,
    [SB_Contact__c]                                      NVARCHAR (25)      NULL,
    [SBQQ__AssetQuantitiesCombined__c]                   BIT                NULL,
    [SBQQ__ContractCoTermination__c]                     NVARCHAR (255)     NULL,
    [SBQQ__CoTermedContractsCombined__c]                 BIT                NULL,
    [SBQQ__CoTerminationEvent__c]                        NVARCHAR (255)     NULL,
    [SBQQ__DefaultOpportunity__c]                        NVARCHAR (18)      NULL,
    [SBQQ__IgnoreParentContractedPrices__c]              BIT                NULL,
    [SBQQ__PreserveBundle__c]                            BIT                NULL,
    [SBQQ__PriceHoldEnd__c]                              DATE               NULL,
    [SBQQ__RenewalModel__c]                              NVARCHAR (255)     NULL,
    [SBQQ__RenewalPricingMethod__c]                      NVARCHAR (255)     NULL,
    [SBQQ__TaxExempt__c]                                 NVARCHAR (255)     NULL,
    [School_Type__c]                                     NVARCHAR (255)     NULL,
    [Service_Area__c]                                    NVARCHAR (MAX)     NULL,
    [SFBD__CollectionsAgent__c]                          NVARCHAR (18)      NULL,
    [SFBD__CollectionsPlanDate__c]                       DATE               NULL,
    [SFBD__CollectionsStatus__c]                         NVARCHAR (255)     NULL,
    [SFBD__DunningMethod__c]                             NVARCHAR (18)      NULL,
    [SFBD__SLA__c]                                       NVARCHAR (255)     NULL,
    [SFBD__UpsellOpportunity__c]                         NVARCHAR (255)     NULL,
    [ShippingCity]                                       NVARCHAR (40)      NULL,
    [ShippingCountry]                                    NVARCHAR (80)      NULL,
    [ShippingCountryCode]                                NVARCHAR (50)      NULL,
    [ShippingGeocodeAccuracy]                            NVARCHAR (50)      NULL,
    [ShippingLatitude]                                   NUMERIC (33, 15)   NULL,
    [ShippingLongitude]                                  NUMERIC (33, 15)   NULL,
    [ShippingPostalCode]                                 NVARCHAR (20)      NULL,
    [ShippingState]                                      NVARCHAR (80)      NULL,
    [ShippingStateCode]                                  NVARCHAR (50)      NULL,
    [ShippingStreet]                                     NVARCHAR (255)     NULL,
    [Sic]                                                NVARCHAR (20)      NULL,
    [SIC_Code__c]                                        NUMERIC (18)       NULL,
    [SIC_Description__c]                                 NVARCHAR (255)     NULL,
    [SicDesc]                                            NVARCHAR (80)      NULL,
    [Site]                                               NVARCHAR (80)      NULL,
    [State_Approved__c]                                  NVARCHAR (255)     NULL,
    [State_Board__c]                                     NVARCHAR (18)      NULL,
    [Strategic_Partner_Address__City__s]                 NVARCHAR (40)      NULL,
    [Strategic_Partner_Address__CountryCode__s]          NVARCHAR (50)      NULL,
    [Strategic_Partner_Address__GeocodeAccuracy__s]      NVARCHAR (80)      NULL,
    [Strategic_Partner_Address__Latitude__s]             NUMERIC (33, 15)   NULL,
    [Strategic_Partner_Address__Longitude__s]            NUMERIC (33, 15)   NULL,
    [Strategic_Partner_Address__PostalCode__s]           NVARCHAR (20)      NULL,
    [Strategic_Partner_Address__StateCode__s]            NVARCHAR (50)      NULL,
    [Strategic_Partner_Address__Street__s]               NVARCHAR (255)     NULL,
    [Strategic_Partner_Commission__c]                    NUMERIC (18)       NULL,
    [Strategic_Partner_Name__c]                          NVARCHAR (255)     NULL,
    [Sub_Account_Record_Type__c]                         NVARCHAR (255)     NULL,
    [Supported_Student_Account__c]                       BIT                NULL,
    [SystemModstamp]                                     DATETIMEOFFSET (0) NULL,
    [TickerSymbol]                                       NVARCHAR (20)      NULL,
    [Tier_Account__c]                                    NUMERIC (18)       NULL,
    [Tuition_Cap__c]                                     NUMERIC (18)       NULL,
    [Type]                                               NVARCHAR (255)     NULL,
    [typeform__Typeform_Form_Mapping__c]                 NVARCHAR (18)      NULL,
    [Vacancies__c]                                       NVARCHAR (50)      NULL,
    [Vendor__c]                                          NVARCHAR (MAX)     NULL,
    [Website]                                            NVARCHAR (255)     NULL,
    [WIOA__c]                                            BIT                NULL,
    [X2nd_Strategic_Partner_Address__City__s]            NVARCHAR (40)      NULL,
    [X2nd_Strategic_Partner_Address__CountryCode__s]     NVARCHAR (50)      NULL,
    [X2nd_Strategic_Partner_Address__GeocodeAccuracy__s] NVARCHAR (80)      NULL,
    [X2nd_Strategic_Partner_Address__Latitude__s]        NUMERIC (33, 15)   NULL,
    [X2nd_Strategic_Partner_Address__Longitude__s]       NUMERIC (33, 15)   NULL,
    [X2nd_Strategic_Partner_Address__PostalCode__s]      NVARCHAR (20)      NULL,
    [X2nd_Strategic_Partner_Address__StateCode__s]       NVARCHAR (50)      NULL,
    [X2nd_Strategic_Partner_Address__Street__s]          NVARCHAR (255)     NULL,
    [X2nd_Strategic_Partner_Commission__c]               NUMERIC (18)       NULL,
    [X2nd_Strategic_Partner_Name__c]                     NVARCHAR (255)     NULL,
    [X3rd_Strategic_Partner_Address__City__s]            NVARCHAR (40)      NULL,
    [X3rd_Strategic_Partner_Address__CountryCode__s]     NVARCHAR (50)      NULL,
    [X3rd_Strategic_Partner_Address__GeocodeAccuracy__s] NVARCHAR (80)      NULL,
    [X3rd_Strategic_Partner_Address__Latitude__s]        NUMERIC (33, 15)   NULL,
    [X3rd_Strategic_Partner_Address__Longitude__s]       NUMERIC (33, 15)   NULL,
    [X3rd_Strategic_Partner_Address__PostalCode__s]      NVARCHAR (20)      NULL,
    [X3rd_Strategic_Partner_Address__StateCode__s]       NVARCHAR (50)      NULL,
    [X3rd_Strategic_Partner_Address__Street__s]          NVARCHAR (255)     NULL,
    [X3rd_Strategic_Partner_Commission__c]               NUMERIC (18)       NULL,
    [X3rd_Strategic_Partner_Name__c]                     NVARCHAR (255)     NULL
);

