CREATE TABLE [dwh].[sf_ContactPRD] (
    [Academic_Email__c]               NVARCHAR (80)   NULL,
    [Academic_External_ID__c]         NVARCHAR (50)   NULL,
    [AccountId]                       NVARCHAR (18)   NULL,
    [Accounting_Status__c]            NVARCHAR (255)  NULL,
    [Alternate_Email__c]              NVARCHAR (80)   NULL,
    [Alternate_Name__c]               NVARCHAR (100)  NULL,
    [Case_Safe_ID_contacts__c]        NVARCHAR (1300) NULL,
    [Birthdate]                       DATE            NULL,
    [Email]                           NVARCHAR (80)   NULL,
    [Department]                      NVARCHAR (80)   NULL,
    [Name]                            NVARCHAR (121)  NULL,
    [Order__c]                        NVARCHAR (18)   NULL,
    [Phone]                           NVARCHAR (40)   NULL,
    [NHA_Registered_email__c]         NVARCHAR (100)  NULL,
    [Academic_Status__c]              NVARCHAR (255)  NULL,
    [FirstName]                       NVARCHAR (40)   NULL,
    [LastName]                        NVARCHAR (80)   NULL,
    [Enrolled_Program__c]             NVARCHAR (100)  NULL,
    [Start_Date__c]                   DATE            NULL,
    [Program_Completion_Date__c]      DATE            NULL,
    [Cleared_for_National_Exam__c]    BIT             NULL,
    [Certification_1_Final_Result__c] NVARCHAR (1300) NULL,
    [Last_LMS_Login_Date__c]          DATE            NULL,
    [LastActivityDate]                DATE            NULL,
    [End_Date__c]                     DATE            NULL,
    [Last_Activity_Completion__c]     DATE            NULL
);

