CREATE TABLE [dwh].[sf_Course] (
    [CreatedById]                        NVARCHAR (18)      NULL,
    [CreatedDate]                        DATETIMEOFFSET (0) NULL,
    [enlighten__Course_Category__c]      NVARCHAR (18)      NULL,
    [enlighten__Course_Creator__c]       NVARCHAR (100)     NULL,
    [enlighten__Course_Description__c]   NVARCHAR (MAX)     NULL,
    [enlighten__Course_End_Date__c]      DATE               NULL,
    [enlighten__Course_Full_Name__c]     NVARCHAR (254)     NULL,
    [enlighten__Course_ID__c]            NVARCHAR (255)     NULL,
    [enlighten__Course_Name_Extended__c] NVARCHAR (255)     NULL,
    [enlighten__Course_Start_Date__c]    DATE               NULL,
    [enlighten__Creation_Date__c]        DATE               NULL,
    [enlighten__Is_Deleted__c]           BIT                NULL,
    [enlighten__MoodleID__c]             NVARCHAR (50)      NULL,
    [enlighten__source__c]               NVARCHAR (255)     NULL,
    [enlighten__Sub_Account__c]          NVARCHAR (255)     NULL,
    [enlighten__Visible__c]              BIT                NULL,
    [Id]                                 NVARCHAR (18)      NULL,
    [IsDeleted]                          BIT                NULL,
    [LastModifiedById]                   NVARCHAR (18)      NULL,
    [LastModifiedDate]                   DATETIMEOFFSET (0) NULL,
    [LastReferencedDate]                 DATETIMEOFFSET (0) NULL,
    [LastViewedDate]                     DATETIMEOFFSET (0) NULL,
    [Name]                               NVARCHAR (80)      NULL,
    [OwnerId]                            NVARCHAR (18)      NULL,
    [Status__c]                          NVARCHAR (255)     NULL,
    [SystemModstamp]                     DATETIMEOFFSET (0) NULL
);

