CREATE TABLE [dwh].[sf_ProgramContactAssigment] (
    [Academic_Status__c]                          NVARCHAR (255)     NULL,
    [Academic_Status_Change_Date__c]              DATE               NULL,
    [Account__c]                                  NVARCHAR (18)      NULL,
    [Accounting_Status__c]                        NVARCHAR (255)     NULL,
    [Added_fee_to_record__c]                      BIT                NULL,
    [Admission_Advisor_Paid_Date__c]              DATE               NULL,
    [Admissions_Advisor__c]                       NVARCHAR (18)      NULL,
    [Amount_Left_to_be_Invoiced__c]               NUMERIC (20, 2)    NULL,
    [Army_IgnitED_End_Date__c]                    DATETIMEOFFSET (0) NULL,
    [Base_Commission_Date_Paid__c]                DATE               NULL,
    [Book_Agreement_Received__c]                  DATE               NULL,
    [Bookings__c]                                 NUMERIC (20, 2)    NULL,
    [Cancelled_Date__c]                           DATE               NULL,
    [Career_Edge_Account_Activation_Date__c]      DATETIMEOFFSET (0) NULL,
    [Career_Service_Status__c]                    NVARCHAR (255)     NULL,
    [Career_Services_Status_Date_Updated__c]      DATE               NULL,
    [CareerStep__c]                               NUMERIC (20, 2)    NULL,
    [Case_Safe_ID__c]                             NVARCHAR (1300)    NULL,
    [CEdge__c]                                    BIT                NULL,
    [CEdge_Date__c]                               DATETIMEOFFSET (0) NULL,
    [Certificate_of_Completion_Display_Name__c]   NVARCHAR (100)     NULL,
    [Certificate_Program_Name__c]                 NVARCHAR (255)     NULL,
    [Certification_Proctor_Preference__c]         NVARCHAR (255)     NULL,
    [Certification_Status__c]                     NVARCHAR (255)     NULL,
    [CG_Adjustment_Amount__c]                     NUMERIC (20, 2)    NULL,
    [CG_Status_Date_Change__c]                    DATE               NULL,
    [Channel__c]                                  NVARCHAR (255)     NULL,
    [Charged_to_EC__c]                            BIT                NULL,
    [ClearGage_Payment_Id__c]                     NVARCHAR (255)     NULL,
    [Clinical_Required__c]                        BIT                NULL,
    [Cohort_Group__c]                             NVARCHAR (50)      NULL,
    [Commission_Date_Paid__c]                     DATE               NULL,
    [Commission_Percentage__c]                    NUMERIC (7, 2)     NULL,
    [Commissionable_Amount__c]                    NUMERIC (20, 2)    NULL,
    [Commissionable_Amount_20__c]                 NUMERIC (18)       NULL,
    [Commissionable_Amount_80__c]                 NUMERIC (18)       NULL,
    [Commissions_Notes__c]                        NVARCHAR (255)     NULL,
    [Completed_Program_in_Full__c]                BIT                NULL,
    [Completion_Email_Sent_Date__c]               DATE               NULL,
    [Confirmed_Placement__c]                      DATE               NULL,
    [Contact_Employment_Status__c]                NVARCHAR (255)     NULL,
    [ContactRecordTypeId__c]                      NVARCHAR (1300)    NULL,
    [Cost_Adjustment__c]                          NUMERIC (20, 2)    NULL,
    [Cost_of_Program__c]                          NUMERIC (20, 2)    NULL,
    [Course_Objects_to_be_shipped__c]             NVARCHAR (255)     NULL,
    [Courseware_Names_Content__c]                 NVARCHAR (MAX)     NULL,
    [CreatedById]                                 NVARCHAR (18)      NULL,
    [CreatedDate]                                 DATETIMEOFFSET (0) NULL,
    [Credit_Card_Fees__c]                         NUMERIC (20, 2)    NULL,
    [CSC_Completion_Date__c]                      DATE               NULL,
    [Cut_Off_Release_Date__c]                     DATE               NULL,
    [Date_Active_EXT_Reported__c]                 DATE               NULL,
    [Date_Active_Reported__c]                     DATE               NULL,
    [Date_Administrative_Withdrawal_Reported__c]  DATE               NULL,
    [Date_Cancelled_Reported__c]                  DATE               NULL,
    [Date_Certificate_of_Completion_Sent_CM__c]   DATE               NULL,
    [Date_Complete_Reported__c]                   DATE               NULL,
    [Date_Congrats_Email_Sent__c]                 DATE               NULL,
    [Date_Deceased_Reported__c]                   DATE               NULL,
    [Date_Dismissed_Reported__c]                  DATE               NULL,
    [Date_Drop_Reported__c]                       DATE               NULL,
    [Date_Enrollment_Reported__c]                 DATE               NULL,
    [Date_Expiration_Reported__c]                 DATE               NULL,
    [Date_Externship_Clinical_Reported__c]        DATE               NULL,
    [Date_Hired__c]                               DATE               NULL,
    [Date_Incactive_Reported__c]                  DATE               NULL,
    [Date_Incomplete_Reported__c]                 DATE               NULL,
    [Date_No_Show_Reported__c]                    DATE               NULL,
    [Date_Non_Complete_Reported__c]               DATE               NULL,
    [Date_of_Cost_Adjustment__c]                  DATETIMEOFFSET (0) NULL,
    [Date_Pass_Reported__c]                       DATE               NULL,
    [Date_Tuition_Refunded__c]                    DATE               NULL,
    [Date_Turned_Assigned__c]                     DATETIMEOFFSET (0) NULL,
    [Date_Turned_Declined__c]                     DATETIMEOFFSET (0) NULL,
    [Date_Turned_Employed__c]                     DATETIMEOFFSET (0) NULL,
    [Date_Turned_Engaged__c]                      DATETIMEOFFSET (0) NULL,
    [Date_Turned_Expired__c]                      DATETIMEOFFSET (0) NULL,
    [Date_Turned_Not_Engaged__c]                  DATETIMEOFFSET (0) NULL,
    [Date_Turned_Ready_to_Hire__c]                DATETIMEOFFSET (0) NULL,
    [Date_Turned_Unresponsive__c]                 DATETIMEOFFSET (0) NULL,
    [Date_Withdrawal_Cancel_Case_Closed__c]       DATE               NULL,
    [Date_Withdrawal_Reported__c]                 DATE               NULL,
    [Days_Past_Program_Completion_Date__c]        NUMERIC (18)       NULL,
    [Declines_Assistance__c]                      BIT                NULL,
    [Declines_Assistance_Date__c]                 DATE               NULL,
    [Down_Payment_Amount__c]                      NUMERIC (18)       NULL,
    [Duration_to_Completion__c]                   NUMERIC (18)       NULL,
    [Email_BOunced__c]                            BIT                NULL,
    [Employer_City__c]                            NVARCHAR (50)      NULL,
    [Employer_Company_Name__c]                    NVARCHAR (100)     NULL,
    [Employer_Phone__c]                           NVARCHAR (40)      NULL,
    [Employer_State__c]                           NVARCHAR (2)       NULL,
    [Employer_Street_Address__c]                  NVARCHAR (100)     NULL,
    [Employer_Zip_Code__c]                        NVARCHAR (12)      NULL,
    [Employment__c]                               NVARCHAR (18)      NULL,
    [Employment_Status_Date_Updated__c]           DATE               NULL,
    [Employment_Verified__c]                      BIT                NULL,
    [End_Date__c]                                 DATE               NULL,
    [enlighten__Assignment_Method__c]             NVARCHAR (255)     NULL,
    [enlighten__Assignment_Method_Detail__c]      NVARCHAR (255)     NULL,
    [enlighten__ComboID__c]                       NVARCHAR (60)      NULL,
    [enlighten__Complete_By__c]                   DATE               NULL,
    [enlighten__Complete_Within_Period__c]        NUMERIC (5)        NULL,
    [enlighten__Complete_Within_Unit__c]          NVARCHAR (255)     NULL,
    [enlighten__Completion_Deadline_Criteria__c]  NVARCHAR (255)     NULL,
    [enlighten__Contact__c]                       NVARCHAR (18)      NULL,
    [enlighten__Last_Access__c]                   DATE               NULL,
    [enlighten__Percent_Complete__c]              NUMERIC (20, 2)    NULL,
    [enlighten__Percent_Complete_by_Course__c]    NUMERIC (20, 2)    NULL,
    [enlighten__Percent_Complete_by_Module__c]    NUMERIC (20, 2)    NULL,
    [enlighten__Program__c]                       NVARCHAR (18)      NULL,
    [enlighten__Program_Complete__c]              BIT                NULL,
    [enlighten__Program_Complete_Date__c]         DATE               NULL,
    [enlighten__Push__c]                          BIT                NULL,
    [Enrolled_Program__c]                         NVARCHAR (1300)    NULL,
    [Enrolled_Program_Code__c]                    NVARCHAR (1300)    NULL,
    [Enrollment_Date__c]                          DATE               NULL,
    [Enrollment_End_Date__c]                      DATE               NULL,
    [Extension_End_Date__c]                       DATE               NULL,
    [External_Referrer_Email_Contact__c]          NVARCHAR (80)      NULL,
    [External_Referrer_Name__c]                   NVARCHAR (100)     NULL,
    [Externship_Start_Date__c]                    DATE               NULL,
    [Externship_Status__c]                        NVARCHAR (255)     NULL,
    [FA_Amount__c]                                NUMERIC (20, 2)    NULL,
    [Facilitator_Fee__c]                          NUMERIC (20, 2)    NULL,
    [Facilitator_Fee_Notes__c]                    NVARCHAR (255)     NULL,
    [Facilitator_Fee_Paid__c]                     NVARCHAR (255)     NULL,
    [Facilitator_Fee_Received_Date__c]            DATE               NULL,
    [Financial_Aid_ID_Number__c]                  NVARCHAR (12)      NULL,
    [Financial_Aid_Received_Date__c]              DATE               NULL,
    [Financial_Status__c]                         NVARCHAR (255)     NULL,
    [Funding_Source__c]                           NVARCHAR (MAX)     NULL,
    [Guild_Status__c]                             NVARCHAR (255)     NULL,
    [Hold_back__c]                                BIT                NULL,
    [Id]                                          NVARCHAR (18)      NULL,
    [Incomplete_Reported__c]                      BIT                NULL,
    [Interest_Payment_Rollup__c]                  NUMERIC (20, 2)    NULL,
    [Invoice_Number__c]                           NVARCHAR (255)     NULL,
    [Invoiced__c]                                 BIT                NULL,
    [Invoiced_Date__c]                            DATE               NULL,
    [Invoiced_Total_Amount__c]                    NUMERIC (20, 2)    NULL,
    [Invoicing_Notes__c]                          NVARCHAR (2500)    NULL,
    [Invoicing_Terms__c]                          NVARCHAR (1300)    NULL,
    [IsDeleted]                                   BIT                NULL,
    [IT_Practice_Labs__c]                         NUMERIC (20, 2)    NULL,
    [ITProTV_Fee__c]                              NUMERIC (10, 2)    NULL,
    [Last_Activity_Completion__c]                 DATE               NULL,
    [Last_Module__c]                              NVARCHAR (255)     NULL,
    [LastActivityDate]                            DATE               NULL,
    [LastModifiedById]                            NVARCHAR (18)      NULL,
    [LastModifiedDate]                            DATETIMEOFFSET (0) NULL,
    [LMS_Financial_Message__c]                    NVARCHAR (400)     NULL,
    [Loan_Terms__c]                               NVARCHAR (MAX)     NULL,
    [McGraw_Hill_Fee__c]                          NUMERIC (10, 2)    NULL,
    [Medcerts_Start_Date__c]                      DATE               NULL,
    [MedTrak_Fee__c]                              NUMERIC (10, 2)    NULL,
    [Metrix__c]                                   NUMERIC (20, 2)    NULL,
    [Multiple_Invoicing_from_Account__c]          NVARCHAR (1300)    NULL,
    [MyCAA_Number__c]                             NVARCHAR (12)      NULL,
    [Name]                                        NVARCHAR (80)      NULL,
    [NASM_Fee__c]                                 NUMERIC (4)        NULL,
    [No_of_Certs_Passed__c]                       NUMERIC (18)       NULL,
    [Non_Complete_Reported__c]                    BIT                NULL,
    [Note__c]                                     NVARCHAR (255)     NULL,
    [Numerical_Invoice_Number__c]                 NUMERIC (18)       NULL,
    [Opened_Welcome_Email__c]                     DATE               NULL,
    [Opt_Out_Date__c]                             DATE               NULL,
    [Opt_Out_Reason__c]                           NVARCHAR (255)     NULL,
    [Order__c]                                    NVARCHAR (18)      NULL,
    [Orientation_complete_email_sent__c]          DATE               NULL,
    [Orientation_complete_SMS_sent__c]            DATE               NULL,
    [Original_Program_Consultant__c]              NVARCHAR (18)      NULL,
    [Original_RWM__c]                             NVARCHAR (18)      NULL,
    [Outstanding_Amount_Due__c]                   NUMERIC (20, 2)    NULL,
    [Parent_Program__c]                           NVARCHAR (1300)    NULL,
    [Pass_Reported__c]                            BIT                NULL,
    [Past_Start_Date__c]                          BIT                NULL,
    [Payment_Amount__c]                           NUMERIC (12, 2)    NULL,
    [Payment_Date__c]                             DATE               NULL,
    [Payment_Month_Cut_Off_Date__c]               DATE               NULL,
    [Payment_Received__c]                         BIT                NULL,
    [Payment_Terms__c]                            NVARCHAR (255)     NULL,
    [Payment_Total_Rollup__c]                     NUMERIC (20, 2)    NULL,
    [PayPal_Email_Address__c]                     NVARCHAR (80)      NULL,
    [PeriopSim_Fee__c]                            NUMERIC (12, 2)    NULL,
    [Post_Training_Employment_Status__c]          NVARCHAR (255)     NULL,
    [Post_Training_Employment_Status_Delete__c]   NVARCHAR (255)     NULL,
    [Post_Training_Employment_Sub_Status__c]      NVARCHAR (255)     NULL,
    [Post_Training_Hourly_Rate__c]                NVARCHAR (255)     NULL,
    [Post_Training_Industry__c]                   NVARCHAR (255)     NULL,
    [Post_Training_Industry_if_Other__c]          NVARCHAR (255)     NULL,
    [Post_Training_Job_Title__c]                  NVARCHAR (255)     NULL,
    [Post_Training_Job_Title_if_Other__c]         NVARCHAR (255)     NULL,
    [Prepaid_in_Full__c]                          BIT                NULL,
    [Product__c]                                  NVARCHAR (18)      NULL,
    [Program_ID_Number__c]                        NVARCHAR (1300)    NULL,
    [Program_Student_Completion_Percentage__c]    NUMERIC (7, 2)     NULL,
    [Program_Student_Target_Completion__c]        NUMERIC (7, 2)     NULL,
    [Program_Target_Completion__c]                NUMERIC (20, 2)    NULL,
    [ProgramCertification__c]                     NVARCHAR (18)      NULL,
    [Ready_to_Place__c]                           DATE               NULL,
    [Recruiting_Fee__c]                           NUMERIC (5)        NULL,
    [Referral_approved_by__c]                     NVARCHAR (18)      NULL,
    [Referral_Email__c]                           NVARCHAR (80)      NULL,
    [Referral_Fee__c]                             NUMERIC (14, 2)    NULL,
    [Referral_Fee_Paid_Date__c]                   DATE               NULL,
    [Referral_Mailing_Address__c]                 NVARCHAR (MAX)     NULL,
    [Referral_Posted__c]                          BIT                NULL,
    [Referral_W9__c]                              BIT                NULL,
    [Referring_Account__c]                        NVARCHAR (18)      NULL,
    [Referring_Team_Member_Contact__c]            NVARCHAR (18)      NULL,
    [Resume_Approved__c]                          BIT                NULL,
    [Resume_Approved_Date__c]                     DATE               NULL,
    [Resume_Received__c]                          BIT                NULL,
    [Resume_Received_Date__c]                     DATE               NULL,
    [Royalty_Fee__c]                              NUMERIC (20, 2)    NULL,
    [Salary__c]                                   NUMERIC (18)       NULL,
    [Scholarship_Amount__c]                       NUMERIC (20, 2)    NULL,
    [Simtics__c]                                  NUMERIC (20, 2)    NULL,
    [SimTutor__c]                                 NUMERIC (20, 2)    NULL,
    [Site_Name__c]                                NVARCHAR (255)     NULL,
    [Skillpath__c]                                NUMERIC (20, 2)    NULL,
    [SkillUp_Fee__c]                              NUMERIC (20, 2)    NULL,
    [SkillUp_ID_Number__c]                        NVARCHAR (255)     NULL,
    [SkillUp_lead__c]                             BIT                NULL,
    [SkillUp_Payment__c]                          NVARCHAR (255)     NULL,
    [SKU1__c]                                     NVARCHAR (255)     NULL,
    [SKU2__c]                                     NVARCHAR (255)     NULL,
    [SKU3__c]                                     NVARCHAR (255)     NULL,
    [Split_Booking_Percentage__c]                 NUMERIC (20, 2)    NULL,
    [Split_Booking_RWM__c]                        NVARCHAR (18)      NULL,
    [SSA_Calendly_Link__c]                        NVARCHAR (255)     NULL,
    [Start_Date__c]                               DATE               NULL,
    [Starting_Employer__c]                        NVARCHAR (255)     NULL,
    [Starting_Employment_Status__c]               NVARCHAR (255)     NULL,
    [Starting_Hourly_Rate__c]                     NVARCHAR (255)     NULL,
    [Starting_Industry__c]                        NVARCHAR (255)     NULL,
    [Starting_Industry_if_Other__c]               NVARCHAR (255)     NULL,
    [Starting_Job_Title__c]                       NVARCHAR (255)     NULL,
    [Starting_Job_Title_if_Other__c]              NVARCHAR (255)     NULL,
    [Student_Advisor__c]                          NVARCHAR (18)      NULL,
    [Student_Advisor_Assigned_Date__c]            DATE               NULL,
    [Student_Advisor_Distributed__c]              BIT                NULL,
    [Student_Advisor_Email__c]                    NVARCHAR (80)      NULL,
    [Student_Advisor_Gateway__c]                  NVARCHAR (18)      NULL,
    [Student_Advisor_Name__c]                     NVARCHAR (50)      NULL,
    [Student_Advisor_Phone__c]                    NVARCHAR (40)      NULL,
    [Student_Payment_Status__c]                   NVARCHAR (255)     NULL,
    [Student_Program_Completion__c]               NUMERIC (20, 2)    NULL,
    [Student_Requests_CS_Contact__c]              BIT                NULL,
    [Student_Responsibility_Amount__c]            NUMERIC (20, 2)    NULL,
    [Student_Responsibility_Amount_Paid__c]       BIT                NULL,
    [Student_Tracking_to_Target_Percentage__c]    NUMERIC (20, 2)    NULL,
    [Student_Used_MedCerts_CS_Services__c]        NVARCHAR (255)     NULL,
    [Subchannel__c]                               NVARCHAR (255)     NULL,
    [Supervisor_Employer_Contact__c]              NVARCHAR (100)     NULL,
    [Supervisor_Employer_Email__c]                NVARCHAR (80)      NULL,
    [SystemModstamp]                              DATETIMEOFFSET (0) NULL,
    [Team_Ignition_Data_Collected__c]             BIT                NULL,
    [Team_Ignition_Record_Updated__c]             DATE               NULL,
    [Total_Cost__c]                               NUMERIC (20, 2)    NULL,
    [TotalSEM__c]                                 NUMERIC (20, 2)    NULL,
    [Tuition_Refunded_Amount__c]                  NUMERIC (20, 2)    NULL,
    [Tuition_Reimbursement_Approval__c]           BIT                NULL,
    [VetBloom__c]                                 NUMERIC (20, 2)    NULL,
    [VitalSource_Fee__c]                          NUMERIC (20, 2)    NULL,
    [Welcome_email_initial_SMS__c]                DATE               NULL,
    [Welcome_email_not_opened_SMS_sent__c]        DATE               NULL,
    [Welcome_email_sent_date__c]                  DATE               NULL,
    [Written_Off__c]                              BIT                NULL,
    [X100_Days_Commissionable_Amount__c]          DATE               NULL,
    [X12_Month_Retention__c]                      DATE               NULL,
    [X14_day_no_progress_email_sent__c]           DATE               NULL,
    [X1st_Payment_Date__c]                        DATE               NULL,
    [X1st_Payment_Recieved__c]                    BIT                NULL,
    [X21_day_no_progress_email_sent__c]           DATE               NULL,
    [X21_day_no_progress_sms_sent__c]             DATE               NULL,
    [X3_months_Retail_Self_pay_100_SMS_sent__c]   DATE               NULL,
    [X4_weeks_Retail_Self_pay_100_SMS_sent__c]    DATE               NULL,
    [X48_hours_unopened_welcome_email_date__c]    DATE               NULL,
    [X6_Month_Retention__c]                       DATE               NULL,
    [X6_months_Retail_Self_pay_100_SMS_sent__c]   DATE               NULL,
    [X6_months_retail_student_hired_SMS_sent__c]  DATE               NULL,
    [X7_day_no_progress_email_sent__c]            DATE               NULL,
    [X7_day_no_progress_sms_sent__c]              DATE               NULL,
    [X72_hours_orientation_not_complete_email__c] DATE               NULL,
    [X72_hours_orientation_not_complete_SMS__c]   DATE               NULL,
    [X9_months_Retail_Self_pay_100_SMS_sent__c]   DATE               NULL,
    [X90_days_after_program_completion__c]        DATE               NULL
);

