CREATE TABLE [dwh].[sf_ProgramAssigment] (
    [Academic_Status__c]                         NVARCHAR (255)  NULL,
    [Academic_Status_Change_Date__c]             DATE            NULL,
    [Accounting_Status__c]                       NVARCHAR (255)  NULL,
    [Added_fee_to_record__c]                     BIT             NULL,
    [Admission_Advisor_Paid_Date__c]             DATE            NULL,
    [Admissions_Advisor__c]                      NVARCHAR (18)   NULL,
    [Amount_Left_to_be_Invoiced__c]              NUMERIC (20, 2) NULL,
    [Base_Commission_Date_Paid__c]               DATE            NULL,
    [Book_Agreement_Received__c]                 DATE            NULL,
    [Bookings__c]                                NUMERIC (20, 2) NULL,
    [Cancelled_Date__c]                          DATE            NULL,
    [Career_Service_Status__c]                   NVARCHAR (255)  NULL,
    [CareerStep__c]                              NUMERIC (20, 2) NULL,
    [Certificate_Program_Name__c]                NVARCHAR (255)  NULL,
    [Certification_Proctor_Preference__c]        NVARCHAR (255)  NULL,
    [Certification_Status__c]                    NVARCHAR (255)  NULL,
    [CG_Adjustment_Amount__c]                    NUMERIC (20, 2) NULL,
    [CG_Status_Date_Change__c]                   DATE            NULL,
    [Channel__c]                                 NVARCHAR (255)  NULL,
    [Charged_to_EC__c]                           BIT             NULL,
    [ClearGage_Payment_Id__c]                    NVARCHAR (255)  NULL,
    [Clinical_Required__c]                       BIT             NULL,
    [Commission_Date_Paid__c]                    DATE            NULL,
    [Commission_Percentage__c]                   NUMERIC (7, 2)  NULL,
    [Commissionable_Amount__c]                   NUMERIC (20, 2) NULL,
    [Commissionable_Amount_20__c]                NUMERIC (18)    NULL,
    [Commissionable_Amount_80__c]                NUMERIC (18)    NULL,
    [Commissions_Notes__c]                       NVARCHAR (255)  NULL,
    [Completed_Externship__c]                    BIT             NULL,
    [Cost_Adjustment__c]                         NUMERIC (20, 2) NULL,
    [Cost_of_Program__c]                         NUMERIC (20, 2) NULL,
    [Course_Objects_to_be_shipped__c]            NVARCHAR (255)  NULL,
    [Courseware_Names_Content__c]                NVARCHAR (MAX)  NULL,
    [CreatedById]                                NVARCHAR (18)   NULL,
    [CreatedDate]                                DATETIME        NULL,
    [Credit_Card_Fees__c]                        NUMERIC (20, 2) NULL,
    [CSC_Completion_Date__c]                     DATE            NULL,
    [Cut_Off_Release_Date__c]                    DATE            NULL,
    [Date_Active_EXT_Reported__c]                DATE            NULL,
    [Date_Active_Reported__c]                    DATE            NULL,
    [Date_Administrative_Withdrawal_Reported__c] DATE            NULL,
    [Date_Cancelled_Reported__c]                 DATE            NULL,
    [Date_Complete_Reported__c]                  DATE            NULL,
    [Date_Deceased_Reported__c]                  DATE            NULL,
    [Date_Dismissed_Reported__c]                 DATE            NULL,
    [Date_Drop_Reported__c]                      DATE            NULL,
    [Date_Enrollment_Reported__c]                DATE            NULL,
    [Date_Expiration_Reported__c]                DATE            NULL,
    [Date_Externship_Clinical_Reported__c]       DATE            NULL,
    [Date_Incactive_Reported__c]                 DATE            NULL,
    [Date_No_Show_Reported__c]                   DATE            NULL,
    [Date_of_Cost_Adjustment__c]                 DATETIME        NULL,
    [Date_Tuition_Refunded__c]                   DATE            NULL,
    [Date_Withdrawal_Cancel_Case_Closed__c]      DATE            NULL,
    [Date_Withdrawal_Reported__c]                DATE            NULL,
    [Days_Past_Program_Completion_Date__c]       NUMERIC (18)    NULL,
    [Down_Payment_Amount__c]                     NUMERIC (18)    NULL,
    [Employer_Relations_Coordinator__c]          NVARCHAR (18)   NULL,
    [Employment_Information__c]                  NVARCHAR (255)  NULL,
    [End_Date__c]                                DATE            NULL,
    [enlighten__Assignment_Method__c]            NVARCHAR (255)  NULL,
    [enlighten__Assignment_Method_Detail__c]     NVARCHAR (255)  NULL,
    [enlighten__ComboID__c]                      NVARCHAR (60)   NULL,
    [enlighten__Complete_By__c]                  DATE            NULL,
    [enlighten__Complete_Within_Period__c]       NUMERIC (5)     NULL,
    [enlighten__Complete_Within_Unit__c]         NVARCHAR (255)  NULL,
    [enlighten__Completion_Deadline_Criteria__c] NVARCHAR (255)  NULL,
    [enlighten__Contact__c]                      NVARCHAR (18)   NULL,
    [enlighten__Last_Access__c]                  DATE            NULL,
    [enlighten__Percent_Complete__c]             NUMERIC (20, 2) NULL,
    [enlighten__Percent_Complete_by_Course__c]   NUMERIC (20, 2) NULL,
    [enlighten__Percent_Complete_by_Module__c]   NUMERIC (20, 2) NULL,
    [enlighten__Program__c]                      NVARCHAR (18)   NULL,
    [enlighten__Program_Complete__c]             BIT             NULL,
    [enlighten__Program_Complete_Date__c]        DATE            NULL,
    [enlighten__Push__c]                         BIT             NULL,
    [Enrolled_Program_Code__c]                   NVARCHAR (1300) NULL,
    [Enrollment_Date__c]                         DATE            NULL,
    [Enrollment_End_Date__c]                     DATE            NULL,
    [ERC_Calendly_Link__c]                       NVARCHAR (255)  NULL,
    [ERC_Email__c]                               NVARCHAR (80)   NULL,
    [ERC_Phone__c]                               NVARCHAR (40)   NULL,
    [Extension_End_Date__c]                      DATE            NULL,
    [External_Referrer_Email_Contact__c]         NVARCHAR (80)   NULL,
    [External_Referrer_Name__c]                  NVARCHAR (100)  NULL,
    [Externship_Account__c]                      NVARCHAR (18)   NULL,
    [Externship_Date_Enrollment_App_Received__c] DATE            NULL,
    [Externship_Date_Enrollment_App_Sent__c]     DATE            NULL,
    [Externship_End_Date__c]                     DATE            NULL,
    [Externship_Initial_Email_Date__c]           DATE            NULL,
    [Externship_Notes__c]                        NVARCHAR (MAX)  NULL,
    [Externship_Opt_Out__c]                      BIT             NULL,
    [Externship_Site__c]                         NVARCHAR (255)  NULL,
    [Externship_Start_Date__c]                   DATE            NULL,
    [Externship_Status__c]                       NVARCHAR (255)  NULL,
    [FA_Amount__c]                               NUMERIC (20, 2) NULL,
    [Facilitator_Fee__c]                         NUMERIC (20, 2) NULL,
    [Facilitator_Fee_Notes__c]                   NVARCHAR (255)  NULL,
    [Facilitator_Fee_Paid__c]                    NVARCHAR (255)  NULL,
    [Facilitator_Fee_Received_Date__c]           DATE            NULL,
    [Financial_Aid_ID_Number__c]                 NVARCHAR (12)   NULL,
    [Financial_Aid_Received_Date__c]             DATE            NULL,
    [Financial_Status__c]                        NVARCHAR (255)  NULL,
    [Funding_Source__c]                          NVARCHAR (MAX)  NULL,
    [Guild_Status__c]                            NVARCHAR (255)  NULL,
    [Hold_back__c]                               BIT             NULL,
    [Id]                                         NVARCHAR (18)   NULL,
    [In_rotation__c]                             BIT             NULL,
    [Interest_Payment_Rollup__c]                 NUMERIC (20, 2) NULL,
    [Invoice_Number__c]                          NVARCHAR (255)  NULL,
    [Invoiced__c]                                BIT             NULL,
    [Invoiced_Date__c]                           DATE            NULL,
    [Invoiced_Total_Amount__c]                   NUMERIC (20, 2) NULL,
    [Invoicing_Notes__c]                         NVARCHAR (2500) NULL,
    [Invoicing_Terms__c]                         NVARCHAR (1300) NULL,
    [IsDeleted]                                  BIT             NULL,
    [Last_Module__c]                             NVARCHAR (255)  NULL,
    [LastActivityDate]                           DATE            NULL,
    [LastModifiedById]                           NVARCHAR (18)   NULL,
    [LastModifiedDate]                           DATETIME        NULL,
    [LMS_Financial_Message__c]                   NVARCHAR (400)  NULL,
    [Loan_Terms__c]                              NVARCHAR (MAX)  NULL,
    [McGraw_Hill_Fee__c]                         NUMERIC (10, 2) NULL,
    [Medcerts_Start_Date__c]                     DATE            NULL,
    [MedTrak_Fee__c]                             NUMERIC (10, 2) NULL,
    [Multiple_Invoicing_from_Account__c]         NVARCHAR (1300) NULL,
    [MyCAA_Number__c]                            NVARCHAR (12)   NULL,
    [Name]                                       NVARCHAR (80)   NULL,
    [NASM_Fee__c]                                NUMERIC (4)     NULL,
    [No_of_Certs_Passed__c]                      NUMERIC (18)    NULL,
    [Note__c]                                    NVARCHAR (255)  NULL,
    [Numerical_Invoice_Number__c]                NUMERIC (18)    NULL,
    [Oder__c]                                    NVARCHAR (18)   NULL,
    [Original_Program_Consultant__c]             NVARCHAR (18)   NULL,
    [Original_RWM__c]                            NVARCHAR (18)   NULL,
    [Outstanding_Amount_Due__c]                  NUMERIC (20, 2) NULL,
    [Parent_Program__c]                          NVARCHAR (1300) NULL,
    [Pass_Reported__c]                           BIT             NULL,
    [Past_Start_Date__c]                         BIT             NULL,
    [Payment_Amount__c]                          NUMERIC (12, 2) NULL,
    [Payment_Date__c]                            DATE            NULL,
    [Payment_Month_Cut_Off_Date__c]              DATE            NULL,
    [Payment_Received__c]                        BIT             NULL,
    [Payment_Terms__c]                           NVARCHAR (255)  NULL,
    [Payment_Total_Rollup__c]                    NUMERIC (20, 2) NULL,
    [PayPal_Email_Address__c]                    NVARCHAR (80)   NULL,
    [Prepaid_in_Full__c]                         BIT             NULL,
    [Primary_Externship_Contact__c]              NVARCHAR (100)  NULL,
    [Product__c]                                 NVARCHAR (18)   NULL,
    [Program_ID_Number__c]                       NVARCHAR (1300) NULL,
    [Program_Student_Completion_Percentage__c]   NUMERIC (7, 2)  NULL,
    [Program_Student_Target_Completion__c]       NUMERIC (7, 2)  NULL,
    [Program_Target_Completion__c]               NUMERIC (20, 2) NULL,
    [Recruiting_Fee__c]                          NUMERIC (5)     NULL,
    [Referral_approved_by__c]                    NVARCHAR (18)   NULL,
    [Referral_Email__c]                          NVARCHAR (80)   NULL,
    [Referral_Fee__c]                            NUMERIC (14, 2) NULL,
    [Referral_Fee_Paid_Date__c]                  DATE            NULL,
    [Referral_Mailing_Address__c]                NVARCHAR (MAX)  NULL,
    [Referral_Posted__c]                         BIT             NULL,
    [Referral_W9__c]                             BIT             NULL,
    [Referring_Account__c]                       NVARCHAR (18)   NULL,
    [Referring_Team_Member_Contact__c]           NVARCHAR (18)   NULL,
    [Requires_Externship__c]                     BIT             NULL,
    [Royalty_Fee__c]                             NUMERIC (20, 2) NULL,
    [RX3000_Week_10_Outreach__c]                 BIT             NULL,
    [RX3000_Week_2_Outreach__c]                  BIT             NULL,
    [Scholarship_Amount__c]                      NUMERIC (20, 2) NULL,
    [Scrubs_and_Stethoscope_Email_Sent_Date__c]  DATE            NULL,
    [Simtics__c]                                 NUMERIC (20, 2) NULL,
    [SkillUp_Fee__c]                             NUMERIC (20, 2) NULL,
    [SkillUp_ID_Number__c]                       NVARCHAR (255)  NULL,
    [SkillUp_lead__c]                            BIT             NULL,
    [SkillUp_Payment__c]                         NVARCHAR (255)  NULL,
    [SKU1__c]                                    NVARCHAR (255)  NULL,
    [SKU2__c]                                    NVARCHAR (255)  NULL,
    [SKU3__c]                                    NVARCHAR (255)  NULL,
    [Split_Booking_Percentage__c]                NUMERIC (20, 2) NULL,
    [Split_Booking_RWM__c]                       NVARCHAR (18)   NULL,
    [Start_Date__c]                              DATE            NULL,
    [Student_Advisor__c]                         NVARCHAR (18)   NULL,
    [Student_Advisor_Assigned_Date__c]           DATE            NULL,
    [Student_Advisor_Distributed__c]             BIT             NULL,
    [Student_Advisor_Email__c]                   NVARCHAR (80)   NULL,
    [Student_Advisor_Gateway__c]                 NVARCHAR (18)   NULL,
    [Student_Advisor_Name__c]                    NVARCHAR (50)   NULL,
    [Student_Advisor_Phone__c]                   NVARCHAR (40)   NULL,
    [Student_Payment_Status__c]                  NVARCHAR (255)  NULL,
    [Student_Program_Completion__c]              NUMERIC (20, 2) NULL,
    [Student_Responsibility_Amount__c]           NUMERIC (20, 2) NULL,
    [Student_Responsibility_Amount_Paid__c]      BIT             NULL,
    [Student_Tracking_to_Target_Percentage__c]   NUMERIC (20, 2) NULL,
    [SystemModstamp]                             DATETIME        NULL,
    [Total_Cost__c]                              NUMERIC (20, 2) NULL,
    [TotalSEM__c]                                NUMERIC (20, 2) NULL,
    [Tuition_Refunded_Amount__c]                 NUMERIC (20, 2) NULL,
    [Tuition_Reimbursement_Approval__c]          BIT             NULL,
    [VA_Externship_Status__c]                    NVARCHAR (255)  NULL,
    [VitalSource_Fee__c]                         NUMERIC (20, 2) NULL,
    [Written_Off__c]                             BIT             NULL,
    [X100_Days_Commissionable_Amount__c]         DATE            NULL,
    [X1st_Payment_Date__c]                       DATE            NULL,
    [X1st_Payment_Recieved__c]                   BIT             NULL
);

