CREATE TABLE [dwh].[sf_Program] (
    [Case_Safe_ID__c]                     NVARCHAR (1300) NULL,
    [Cost__c]                             NUMERIC (9, 2)  NULL,
    [CreatedById]                         NVARCHAR (18)   NULL,
    [CreatedDate]                         SMALLDATETIME   NULL,
    [Duration__c]                         NUMERIC (4)     NULL,
    [enlighten__Available_From__c]        DATE            NULL,
    [enlighten__Available_To_Students__c] BIT             NULL,
    [enlighten__Available_Until__c]       DATE            NULL,
    [enlighten__Course_Category__c]       NVARCHAR (18)   NULL,
    [enlighten__Endnote__c]               NVARCHAR (MAX)  NULL,
    [enlighten__MoodleID__c]              NVARCHAR (10)   NULL,
    [enlighten__Program_ID_Number__c]     NVARCHAR (100)  NULL,
    [enlighten__Short_Name__c]            NVARCHAR (100)  NULL,
    [enlighten__Summary__c]               NVARCHAR (MAX)  NULL,
    [enlighten__Visible__c]               BIT             NULL,
    [Id]                                  NVARCHAR (18)   NULL,
    [IsDeleted]                           BIT             NULL,
    [LastActivityDate]                    DATE            NULL,
    [LastModifiedById]                    NVARCHAR (18)   NULL,
    [LastModifiedDate]                    SMALLDATETIME   NULL,
    [LastReferencedDate]                  SMALLDATETIME   NULL,
    [LastViewedDate]                      SMALLDATETIME   NULL,
    [Name]                                NVARCHAR (80)   NULL,
    [OwnerId]                             NVARCHAR (18)   NULL,
    [Parent_Program__c]                   NVARCHAR (255)  NULL,
    [Program_Certificate_Name__c]         NVARCHAR (255)  NULL,
    [SystemModstamp]                      SMALLDATETIME   NULL
);

