CREATE TABLE [etl].[NHA_Practice_Test] (
    [First_Name]                                    VARCHAR (50) NULL,
    [Last_Name]                                     VARCHAR (50) NULL,
    [Student_Email]                                 VARCHAR (50) NULL,
    [Cert_Product]                                  VARCHAR (50) NULL,
    [Approval_Date]                                 VARCHAR (50) NULL,
    [Data_Current_As_Of]                            VARCHAR (50) NULL,
    [EnrolledInCourse]                              VARCHAR (50) NULL,
    [Acct_Created_Date]                             VARCHAR (50) NULL,
    [AttemptUserID]                                 VARCHAR (50) NULL,
    [Product_Number]                                VARCHAR (50) NULL,
    [First_Exam_Date]                               VARCHAR (50) NULL,
    [1st_Practice_Test_Attempt Date]                VARCHAR (50) NULL,
    [1st_Practice_Test_Score]                       VARCHAR (50) NULL,
    [1st_Practice_Test_Percent]                     VARCHAR (50) NULL,
    [1st_Practice_Test_Attempt Focused Review Time] VARCHAR (50) NULL,
    [2nd_Practice_Test_Attempt Date]                VARCHAR (50) NULL,
    [2nd_Practice_Test_Score]                       VARCHAR (50) NULL,
    [2nd_Practice_Test_Percent]                     VARCHAR (50) NULL,
    [2nd_Practice_Test_Attempt Focused Review Time] VARCHAR (50) NULL,
    [3rd_Practice_Test_Attempt Date]                VARCHAR (50) NULL,
    [3rd_Practice_Test_Score]                       VARCHAR (50) NULL,
    [3rd_Practice_Test_Percent]                     VARCHAR (50) NULL,
    [3rd_Practice_Test_Attempt Focused Review Time] VARCHAR (50) NULL,
    [4th_Practice_Test_Attempt Date]                VARCHAR (50) NULL,
    [4th_Practice_Test_Score]                       VARCHAR (50) NULL,
    [4th_Practice_Test_Percent]                     VARCHAR (50) NULL,
    [4th_Practice_Test_Attempt Focused Review Time] VARCHAR (50) NULL,
    [5th_Practice_Test_Attempt Date]                VARCHAR (50) NULL,
    [5th_Practice_Test_Score]                       VARCHAR (50) NULL,
    [5th_Practice_Test_Percent]                     VARCHAR (50) NULL,
    [5th_Practice_Test_Attempt Focused Review Time] VARCHAR (50) NULL,
    [6th_Practice_Test_Attempt Date]                VARCHAR (50) NULL,
    [6th_Practice_Test_Score]                       VARCHAR (50) NULL,
    [6th_Practice_Test_Percent]                     VARCHAR (50) NULL,
    [6th_Practice_Test_Attempt Focused Review Time] VARCHAR (50) NULL,
    [Institution]                                   VARCHAR (50) NULL,
    [ProductNumber]                                 VARCHAR (50) NULL,
    [Score]                                         VARCHAR (50) NULL,
    [NHA Exam Registration Date]                    VARCHAR (50) NULL,
    [Exam_Order_Taken]                              VARCHAR (50) NULL,
    [Mode_of_Testing]                               VARCHAR (50) NULL,
    [Planned_Exam_Date]                             VARCHAR (50) NULL,
    [Actual_Exam_Date]                              VARCHAR (50) NULL,
    [Exam_Result]                                   VARCHAR (50) NULL,
    [Cetification_#_Awarded]                        VARCHAR (50) NULL,
    [Status]                                        VARCHAR (50) NULL
);

