CREATE TABLE [dbo].[MedCerts Practice Exams Full History] (
    [First Name]                                    VARCHAR (255) NULL,
    [Last Name]                                     VARCHAR (255) NULL,
    [Student Email]                                 VARCHAR (255) NULL,
    [EnrolledInCourse]                              VARCHAR (255) NULL,
    [Acct Created Date]                             VARCHAR (255) NULL,
    [Cert Product]                                  VARCHAR (255) NULL,
    [AttemptUserID]                                 VARCHAR (255) NULL,
    [Product Number]                                VARCHAR (255) NULL,
    [First Exam Date]                               VARCHAR (255) NULL,
    [Approval Date]                                 VARCHAR (255) NULL,
    [1st Practice Test Attempt Date]                VARCHAR (50)  NULL,
    [1st Practice Test Score]                       VARCHAR (50)  NULL,
    [1st Practice Test Percent]                     VARCHAR (50)  NULL,
    [1st Practice Test Attempt Focused Review Time] VARCHAR (50)  NULL,
    [2nd Practice Test Attempt Date]                VARCHAR (50)  NULL,
    [2nd Practice Test Score]                       VARCHAR (50)  NULL,
    [2nd Practice Test Percent]                     VARCHAR (50)  NULL,
    [2nd Practice Test Attempt Focused Review Time] VARCHAR (50)  NULL,
    [3rd Practice Test Attempt Date]                VARCHAR (50)  NULL,
    [3rd Practice Test Score]                       VARCHAR (50)  NULL,
    [3rd Practice Test Percent]                     VARCHAR (50)  NULL,
    [3rd Practice Test Attempt Focused Review Time] VARCHAR (50)  NULL,
    [4th Practice Test Attempt Date]                VARCHAR (50)  NULL,
    [4th Practice Test Score]                       VARCHAR (50)  NULL,
    [4th Practice Test Percent]                     VARCHAR (50)  NULL,
    [4th Practice Test Attempt Focused Review Time] VARCHAR (50)  NULL,
    [5th Practice Test Attempt Date]                VARCHAR (50)  NULL,
    [5th Practice Test Score]                       VARCHAR (50)  NULL,
    [5th Practice Test Percent]                     VARCHAR (50)  NULL,
    [5th Practice Test Attempt Focused Review Time] VARCHAR (50)  NULL,
    [6th Practice Test Attempt Date]                VARCHAR (50)  NULL,
    [6th Practice Test Score]                       VARCHAR (50)  NULL,
    [6th Practice Test Percent]                     VARCHAR (50)  NULL,
    [6th Practice Test Attempt Focused Review Time] VARCHAR (50)  NULL,
    [Data Current As Of]                            VARCHAR (50)  NULL
);

